/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/wfgraph-theme.ts
 * Command: astryx theme build src/theme/wfgraph-theme.ts
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.4.5
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const wfgraphTheme: DefinedTheme;
