/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/wfgraph-theme.ts
 * Command: astryx theme build src/theme/wfgraph-theme.ts
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.4.5
 */

/**
 * wfgraph theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { wfgraphTheme } from './wfgraph';
 *   import './wfgraph.css';
 */
export const wfgraphTheme = {
  name: 'wfgraph',
  __built: true,
  tokens: {
    "--color-neutral": "light-dark(#1B1B1F1A, #E2E2E833)",
    "--color-background-surface": "light-dark(oklch(1 0 0), oklch(0.205 0 0))",
    "--color-background-body": "light-dark(oklch(1 0 0), oklch(0 0 0))",
    "--color-overlay": "light-dark(#1B1B1F66, #1B1B1F99)",
    "--color-overlay-hover": "light-dark(#1B1B1F0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1B1B1F1A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(oklch(0.97 0 0), oklch(0.15 0 0))",
    "--color-text-primary": "light-dark(oklch(0.145 0 0), oklch(0.98 0 0))",
    "--color-text-secondary": "light-dark(oklch(0.556 0 0), oklch(0.65 0 0))",
    "--color-text-disabled": "light-dark(#8F909A, #5D5E67)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#1B1B1F, #E2E2E8)",
    "--color-icon-secondary": "light-dark(#46464F, #AAAAB5)",
    "--color-icon-disabled": "light-dark(#8F909A, #5D5E67)",
    "--color-background-card": "light-dark(oklch(1 0 0), oklch(0.205 0 0))",
    "--color-background-popover": "light-dark(oklch(1 0 0), oklch(0.205 0 0))",
    "--color-background-inverted": "light-dark(#1B1B1F, #FCFCFF)",
    "--color-border": "light-dark(oklch(0.922 0 0), oklch(0.27 0 0))",
    "--color-border-emphasized": "light-dark(#92929D, #676771)",
    "--color-skeleton": "light-dark(#AAAAB5, #46464F)",
    "--color-track": "light-dark(#AAAAB5, #46464F)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-family-body": "\"Geist Variable\", ui-sans-serif, system-ui, -apple-system, sans-serif",
    "--font-family-heading": "\"Geist Variable\", ui-sans-serif, system-ui, -apple-system, sans-serif",
    "--font-family-code": "\"Geist Mono Variable\", ui-monospace, SFMono-Regular, monospace",
    "--color-accent": "light-dark(oklch(0.205 0 0), oklch(0.98 0 0))",
    "--color-accent-muted": "light-dark(#1717171A, #F8F8F83F)",
    "--color-on-accent": "light-dark(oklch(0.985 0 0), oklch(0.09 0 0))"
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
