import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";

const migrationsDir = resolve("packages/core/drizzle-sqlite");
const manifestFile = resolve(
  "packages/core/src/backend/persistence/sqlite/generated-migrations.ts"
);
const database = new DatabaseSync(":memory:");

const descendingIndexes = new Map<string, readonly [string, number][]>([
  [
    "executions_workflow_started_idx",
    [
      ["workflow_id", 0],
      ["started_at", 1],
      ["id", 1],
    ],
  ],
  [
    "executions_started_idx",
    [
      ["started_at", 1],
      ["id", 1],
    ],
  ],
  [
    "logs_execution_timestamp_idx",
    [
      ["execution_id", 0],
      ["timestamp", 1],
    ],
  ],
  [
    "events_execution_created_idx",
    [
      ["execution_id", 0],
      ["created_at", 1],
    ],
  ],
  [
    "events_workflow_type_created_idx",
    [
      ["workflow_id", 0],
      ["event_type", 0],
      ["created_at", 1],
    ],
  ],
]);

try {
  // A migration folder name is a timestamp-prefixed identifier, so code-unit
  // order is the order the migrations run in. compareText orders text a person
  // reads, and root scripts have no es-toolkit dependency for sortBy.
  const migrationDirectories = readdirSync(migrationsDir, {
    withFileTypes: true,
  })
    .filter((entry) => entry.isDirectory())
    .toSorted((left, right) =>
      left.name < right.name ? -1 : left.name > right.name ? 1 : 0
    );
  const migrations = migrationDirectories.map((entry) => {
    const migrationSql = readFileSync(
      resolve(migrationsDir, entry.name, "migration.sql"),
      "utf8"
    );
    const timestamp = entry.name.slice(0, 14);
    const folderMillis = Date.UTC(
      Number(timestamp.slice(0, 4)),
      Number(timestamp.slice(4, 6)) - 1,
      Number(timestamp.slice(6, 8)),
      Number(timestamp.slice(8, 10)),
      Number(timestamp.slice(10, 12)),
      Number(timestamp.slice(12, 14))
    );
    return {
      sql: migrationSql.split("--> statement-breakpoint"),
      bps: true,
      folderMillis,
      hash: createHash("sha256").update(migrationSql).digest("hex"),
      name: entry.name,
    };
  });
  writeFileSync(
    manifestFile,
    `// Generated by scripts/validate-sqlite-migrations.ts. Do not edit.\n` +
      `import type { MigrationMeta } from "drizzle-orm/migrator";\n\n` +
      `export const sqliteMigrations = [\n${migrations
        .map(
          (migration) => `  {
    sql: [
${migration.sql.map((statement) => `      ${JSON.stringify(statement)},`).join("\n")}
    ],
    bps: true,
    folderMillis: ${migration.folderMillis},
    hash: ${JSON.stringify(migration.hash)},
    name: ${JSON.stringify(migration.name)},
  },`
        )
        .join("\n")}\n] satisfies readonly MigrationMeta[];\n`
  );

  const migrationFiles = migrationDirectories.map((entry) =>
    resolve(migrationsDir, entry.name, "migration.sql")
  );

  if (migrationFiles.length === 0) {
    throw new Error("No SQLite migrations found");
  }
  for (const migrationFile of migrationFiles) {
    database.exec(readFileSync(migrationFile, "utf8"));
  }

  const tables = database
    .prepare(
      `SELECT name, sql FROM sqlite_master
       WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
       ORDER BY name`
    )
    .all()
    .map((row) => {
      if (typeof row.name !== "string" || typeof row.sql !== "string") {
        throw new Error("SQLite returned an invalid table definition");
      }
      return { name: row.name, sql: row.sql };
    });
  for (const table of tables) {
    if (!/\) STRICT(?:, WITHOUT ROWID)?$/i.test(table.sql)) {
      throw new Error(`SQLite table ${table.name} is not STRICT`);
    }
  }

  const subscriptions = tables.find(
    (table) => table.name === "workflow_event_subscriptions"
  );
  if (!subscriptions?.sql.match(/\) STRICT, WITHOUT ROWID$/i)) {
    throw new Error(
      "SQLite table workflow_event_subscriptions is not WITHOUT ROWID"
    );
  }

  for (const [indexName, expectedColumns] of descendingIndexes) {
    const columns = database
      .prepare(
        "SELECT name, desc FROM pragma_index_xinfo(?) WHERE key = 1 ORDER BY seqno"
      )
      .all(indexName)
      .map((row) => [row.name, row.desc]);
    if (JSON.stringify(columns) !== JSON.stringify(expectedColumns)) {
      throw new Error(`SQLite index ${indexName} lost its sort direction`);
    }
  }
} finally {
  database.close();
}
